/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Liveness probe */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Default Response */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/cameras": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List cameras with filters, cursor pagination and PostGIS bbox search */
        get: {
            parameters: {
                query?: {
                    departmentId?: string;
                    district?: string;
                    cameraType?: "analog" | "ip";
                    mount?: "static" | "mobile";
                    adapterKind?: "hls" | "rtsp" | "onvif" | "whep" | "nvr" | "file";
                    status?: "unknown" | "online" | "degraded" | "offline";
                    geometryClass?: "anpr_viable" | "detection_only" | "unclassified";
                    trustMin?: number;
                    trustMax?: number;
                    bbox?: string;
                    q?: string;
                    cursor?: string;
                    limit?: number;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Default Response */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            data: {
                                /** Format: uuid */
                                id: string;
                                externalId: string;
                                name: string;
                                /** Format: uuid */
                                departmentId: string | null;
                                departmentCode: string | null;
                                lat: number | null;
                                lon: number | null;
                                address: string | null;
                                district: string | null;
                                /** @enum {string} */
                                cameraType: "analog" | "ip";
                                /** @enum {string} */
                                mount: "static" | "mobile";
                                /** @enum {string} */
                                geometryClass: "anpr_viable" | "detection_only" | "unclassified";
                                declaredCodec: string | null;
                                declaredFps: number | null;
                                declaredResolution: string | null;
                                vendor: string | null;
                                vmsPlatform: string | null;
                                retentionDays: number | null;
                                /** @enum {string|null} */
                                storageType: "cloud" | "local" | null;
                                /** @enum {string} */
                                adapterKind: "hls" | "rtsp" | "onvif" | "whep" | "nvr" | "file";
                                endpoints: {
                                    [key: string]: string;
                                };
                                /** @enum {string} */
                                status: "unknown" | "online" | "degraded" | "offline";
                                /** @enum {string} */
                                catalogueStatus: "active" | "absent";
                                trustScore: number | null;
                                /** @enum {string|null} */
                                band: "trusted" | "degraded" | "untrusted" | "dead" | null;
                                onboardedAt: string;
                                updatedAt: string;
                            }[];
                            nextCursor: string | null;
                            limit: number;
                        };
                    };
                };
                /** @description Default Response */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            error: string;
                            message: string;
                            allowed?: string[];
                            details?: {
                                field: string;
                                message: string;
                            }[];
                        };
                    };
                };
                /** @description Default Response */
                403: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            error: string;
                            message: string;
                            allowed?: string[];
                            details?: {
                                field: string;
                                message: string;
                            }[];
                        };
                    };
                };
            };
        };
        put?: never;
        /** Manual single-camera onboarding */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        externalId: string;
                        name: string;
                        /** Format: uuid */
                        departmentId?: string | null;
                        lat?: number | null;
                        lon?: number | null;
                        address?: string | null;
                        district?: string | null;
                        /**
                         * @default ip
                         * @enum {string}
                         */
                        cameraType?: "analog" | "ip";
                        /**
                         * @default static
                         * @enum {string}
                         */
                        mount?: "static" | "mobile";
                        /**
                         * @default unclassified
                         * @enum {string}
                         */
                        geometryClass?: "anpr_viable" | "detection_only" | "unclassified";
                        declaredCodec?: string | null;
                        declaredFps?: number | null;
                        declaredResolution?: string | null;
                        vendor?: string | null;
                        vmsPlatform?: string | null;
                        retentionDays?: number | null;
                        /** @enum {string|null} */
                        storageType?: "cloud" | "local" | null;
                        /** @enum {string} */
                        adapterKind: "hls" | "rtsp" | "onvif" | "whep" | "nvr" | "file";
                        /** @default {} */
                        endpoints?: {
                            [key: string]: string;
                        };
                    };
                };
            };
            responses: {
                /** @description Default Response */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            /** Format: uuid */
                            id: string;
                            externalId: string;
                            name: string;
                            /** Format: uuid */
                            departmentId: string | null;
                            departmentCode: string | null;
                            lat: number | null;
                            lon: number | null;
                            address: string | null;
                            district: string | null;
                            /** @enum {string} */
                            cameraType: "analog" | "ip";
                            /** @enum {string} */
                            mount: "static" | "mobile";
                            /** @enum {string} */
                            geometryClass: "anpr_viable" | "detection_only" | "unclassified";
                            declaredCodec: string | null;
                            declaredFps: number | null;
                            declaredResolution: string | null;
                            vendor: string | null;
                            vmsPlatform: string | null;
                            retentionDays: number | null;
                            /** @enum {string|null} */
                            storageType: "cloud" | "local" | null;
                            /** @enum {string} */
                            adapterKind: "hls" | "rtsp" | "onvif" | "whep" | "nvr" | "file";
                            endpoints: {
                                [key: string]: string;
                            };
                            /** @enum {string} */
                            status: "unknown" | "online" | "degraded" | "offline";
                            /** @enum {string} */
                            catalogueStatus: "active" | "absent";
                            trustScore: number | null;
                            /** @enum {string|null} */
                            band: "trusted" | "degraded" | "untrusted" | "dead" | null;
                            onboardedAt: string;
                            updatedAt: string;
                        };
                    };
                };
                /** @description Default Response */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            error: string;
                            message: string;
                            allowed?: string[];
                            details?: {
                                field: string;
                                message: string;
                            }[];
                        };
                    };
                };
                /** @description Default Response */
                403: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            error: string;
                            message: string;
                            allowed?: string[];
                            details?: {
                                field: string;
                                message: string;
                            }[];
                        };
                    };
                };
                /** @description Default Response */
                409: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            error: string;
                            message: string;
                            allowed?: string[];
                            details?: {
                                field: string;
                                message: string;
                            }[];
                        };
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/cameras/export": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Export the registry as CSV or JSON — Model 1 sample metadata dataset */
        get: {
            parameters: {
                query?: {
                    format?: "csv" | "json";
                    departmentId?: string;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Default Response */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/cameras/bulk": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Bulk import from CSV or JSON, transactional per batch with a per-row report */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Default Response */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            received: number;
                            imported: number;
                            created: number;
                            updated: number;
                            rejected: {
                                row: number;
                                externalId: string | null;
                                errors: {
                                    field: string;
                                    message: string;
                                }[];
                            }[];
                            /** @enum {string} */
                            format: "csv" | "json";
                            committed: boolean;
                        };
                    };
                };
                /** @description Default Response */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            error: string;
                            message: string;
                            allowed?: string[];
                            details?: {
                                field: string;
                                message: string;
                            }[];
                        };
                    };
                };
                /** @description Default Response */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            error: string;
                            message: string;
                            allowed?: string[];
                            details?: {
                                field: string;
                                message: string;
                            }[];
                        };
                    };
                };
                /** @description Default Response */
                403: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            error: string;
                            message: string;
                            allowed?: string[];
                            details?: {
                                field: string;
                                message: string;
                            }[];
                        };
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/cameras/onboard-from-catalogue": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Pull the upstream catalogue and sync it into the registry */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        /** Format: uuid */
                        departmentId?: string | null;
                        /**
                         * @default hls
                         * @enum {string}
                         */
                        adapterKind?: "hls" | "rtsp" | "onvif" | "whep" | "nvr" | "file";
                    };
                };
            };
            responses: {
                /** @description Default Response */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            /** Format: uuid */
                            runId: string;
                            source: string;
                            shape: string | null;
                            fetched: number;
                            created: number;
                            added: number;
                            updated: number;
                            unchanged: number;
                            wentAbsent: number;
                            returned: number;
                            skipped: number;
                            rejected: {
                                row: number;
                                externalId: string | null;
                                errors: {
                                    field: string;
                                    message: string;
                                }[];
                            }[];
                        };
                    };
                };
                /** @description Default Response */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            error: string;
                            message: string;
                            allowed?: string[];
                            details?: {
                                field: string;
                                message: string;
                            }[];
                        };
                    };
                };
                /** @description Default Response */
                403: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            error: string;
                            message: string;
                            allowed?: string[];
                            details?: {
                                field: string;
                                message: string;
                            }[];
                        };
                    };
                };
                /** @description Default Response */
                502: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            error: string;
                            message: string;
                            allowed?: string[];
                            details?: {
                                field: string;
                                message: string;
                            }[];
                        };
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/cameras/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Camera detail with latest measured health and the declared-vs-measured delta */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Default Response */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            /** Format: uuid */
                            id: string;
                            externalId: string;
                            name: string;
                            /** Format: uuid */
                            departmentId: string | null;
                            departmentCode: string | null;
                            lat: number | null;
                            lon: number | null;
                            address: string | null;
                            district: string | null;
                            /** @enum {string} */
                            cameraType: "analog" | "ip";
                            /** @enum {string} */
                            mount: "static" | "mobile";
                            /** @enum {string} */
                            geometryClass: "anpr_viable" | "detection_only" | "unclassified";
                            declaredCodec: string | null;
                            declaredFps: number | null;
                            declaredResolution: string | null;
                            vendor: string | null;
                            vmsPlatform: string | null;
                            retentionDays: number | null;
                            /** @enum {string|null} */
                            storageType: "cloud" | "local" | null;
                            /** @enum {string} */
                            adapterKind: "hls" | "rtsp" | "onvif" | "whep" | "nvr" | "file";
                            endpoints: {
                                [key: string]: string;
                            };
                            /** @enum {string} */
                            status: "unknown" | "online" | "degraded" | "offline";
                            /** @enum {string} */
                            catalogueStatus: "active" | "absent";
                            trustScore: number | null;
                            /** @enum {string|null} */
                            band: "trusted" | "degraded" | "untrusted" | "dead" | null;
                            onboardedAt: string;
                            updatedAt: string;
                            latestHealth: {
                                checkedAt: string;
                                connectable: boolean;
                                decodable: boolean;
                                measuredFps: number | null;
                                actualResolution: string | null;
                                actualCodec: string | null;
                                nightUsable: boolean | null;
                                ptsDriftMs: number | null;
                                trustScore: number | null;
                                breakdown: {
                                    [key: string]: unknown;
                                };
                            } | null;
                            declaredVsMeasured: {
                                fpsDeclared: number | null;
                                fpsMeasured: number | null;
                                fpsDelta: number | null;
                                resolutionDeclared: string | null;
                                resolutionMeasured: string | null;
                                resolutionMatches: boolean | null;
                                codecDeclared: string | null;
                                codecMeasured: string | null;
                                codecMatches: boolean | null;
                            } | null;
                        };
                    };
                };
                /** @description Default Response */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            error: string;
                            message: string;
                            allowed?: string[];
                            details?: {
                                field: string;
                                message: string;
                            }[];
                        };
                    };
                };
                /** @description Default Response */
                403: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            error: string;
                            message: string;
                            allowed?: string[];
                            details?: {
                                field: string;
                                message: string;
                            }[];
                        };
                    };
                };
                /** @description Default Response */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            error: string;
                            message: string;
                            allowed?: string[];
                            details?: {
                                field: string;
                                message: string;
                            }[];
                        };
                    };
                };
            };
        };
        put?: never;
        post?: never;
        /** Soft delete — the row is retained as provenance for existing sightings */
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Default Response */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            /** Format: uuid */
                            id: string;
                            /** @enum {boolean} */
                            deleted: true;
                            deletedAt: string;
                        };
                    };
                };
                /** @description Default Response */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            error: string;
                            message: string;
                            allowed?: string[];
                            details?: {
                                field: string;
                                message: string;
                            }[];
                        };
                    };
                };
                /** @description Default Response */
                403: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            error: string;
                            message: string;
                            allowed?: string[];
                            details?: {
                                field: string;
                                message: string;
                            }[];
                        };
                    };
                };
                /** @description Default Response */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            error: string;
                            message: string;
                            allowed?: string[];
                            details?: {
                                field: string;
                                message: string;
                            }[];
                        };
                    };
                };
            };
        };
        options?: never;
        head?: never;
        /** Update camera metadata */
        patch: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        name?: string;
                        /** Format: uuid */
                        departmentId?: string | null;
                        lat?: number | null;
                        lon?: number | null;
                        address?: string | null;
                        district?: string | null;
                        /**
                         * @default ip
                         * @enum {string}
                         */
                        cameraType?: "analog" | "ip";
                        /**
                         * @default static
                         * @enum {string}
                         */
                        mount?: "static" | "mobile";
                        /**
                         * @default unclassified
                         * @enum {string}
                         */
                        geometryClass?: "anpr_viable" | "detection_only" | "unclassified";
                        declaredCodec?: string | null;
                        declaredFps?: number | null;
                        declaredResolution?: string | null;
                        vendor?: string | null;
                        vmsPlatform?: string | null;
                        retentionDays?: number | null;
                        /** @enum {string|null} */
                        storageType?: "cloud" | "local" | null;
                        /** @enum {string} */
                        adapterKind?: "hls" | "rtsp" | "onvif" | "whep" | "nvr" | "file";
                        /** @default {} */
                        endpoints?: {
                            [key: string]: string;
                        };
                    };
                };
            };
            responses: {
                /** @description Default Response */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            /** Format: uuid */
                            id: string;
                            externalId: string;
                            name: string;
                            /** Format: uuid */
                            departmentId: string | null;
                            departmentCode: string | null;
                            lat: number | null;
                            lon: number | null;
                            address: string | null;
                            district: string | null;
                            /** @enum {string} */
                            cameraType: "analog" | "ip";
                            /** @enum {string} */
                            mount: "static" | "mobile";
                            /** @enum {string} */
                            geometryClass: "anpr_viable" | "detection_only" | "unclassified";
                            declaredCodec: string | null;
                            declaredFps: number | null;
                            declaredResolution: string | null;
                            vendor: string | null;
                            vmsPlatform: string | null;
                            retentionDays: number | null;
                            /** @enum {string|null} */
                            storageType: "cloud" | "local" | null;
                            /** @enum {string} */
                            adapterKind: "hls" | "rtsp" | "onvif" | "whep" | "nvr" | "file";
                            endpoints: {
                                [key: string]: string;
                            };
                            /** @enum {string} */
                            status: "unknown" | "online" | "degraded" | "offline";
                            /** @enum {string} */
                            catalogueStatus: "active" | "absent";
                            trustScore: number | null;
                            /** @enum {string|null} */
                            band: "trusted" | "degraded" | "untrusted" | "dead" | null;
                            onboardedAt: string;
                            updatedAt: string;
                        };
                    };
                };
                /** @description Default Response */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            error: string;
                            message: string;
                            allowed?: string[];
                            details?: {
                                field: string;
                                message: string;
                            }[];
                        };
                    };
                };
                /** @description Default Response */
                403: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            error: string;
                            message: string;
                            allowed?: string[];
                            details?: {
                                field: string;
                                message: string;
                            }[];
                        };
                    };
                };
                /** @description Default Response */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            error: string;
                            message: string;
                            allowed?: string[];
                            details?: {
                                field: string;
                                message: string;
                            }[];
                        };
                    };
                };
            };
        };
        trace?: never;
    };
    "/api/v1/departments": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List departments with their live camera counts */
        get: {
            parameters: {
                query?: {
                    limit?: number;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Default Response */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            data: {
                                /** Format: uuid */
                                id: string;
                                code: string;
                                name: string;
                                contactJson: {
                                    [key: string]: unknown;
                                };
                                cameraCount: number;
                                createdAt: string;
                            }[];
                            nextCursor: string | null;
                            limit: number;
                        };
                    };
                };
                /** @description Default Response */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            error: string;
                            message: string;
                            allowed?: string[];
                            details?: {
                                field: string;
                                message: string;
                            }[];
                        };
                    };
                };
                /** @description Default Response */
                403: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            error: string;
                            message: string;
                            allowed?: string[];
                            details?: {
                                field: string;
                                message: string;
                            }[];
                        };
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/sync/reports": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Catalogue sync runs, most recent first */
        get: {
            parameters: {
                query?: {
                    limit?: number;
                    cursor?: string;
                    ok?: boolean;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Default Response */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            items: {
                                /** Format: uuid */
                                id: string;
                                source: string;
                                /** Format: uuid */
                                departmentId: string | null;
                                startedAt: string;
                                finishedAt: string | null;
                                durationMs: number | null;
                                ok: boolean;
                                shape: string | null;
                                trigger: string;
                                fetched: number;
                                added: number;
                                updated: number;
                                unchanged: number;
                                wentAbsent: number;
                                returned: number;
                                skipped: number;
                                rejected: number;
                                error: string | null;
                                rejections: {
                                    row: number;
                                    externalId: string | null;
                                    errors: {
                                        field: string;
                                        message: string;
                                    }[];
                                }[];
                                rawPayload?: unknown;
                                hasRawPayload?: boolean;
                            }[];
                            nextCursor: string | null;
                        };
                    };
                };
                /** @description Default Response */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            error: string;
                            message: string;
                            allowed?: string[];
                            details?: {
                                field: string;
                                message: string;
                            }[];
                        };
                    };
                };
                /** @description Default Response */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            error: string;
                            message: string;
                            allowed?: string[];
                            details?: {
                                field: string;
                                message: string;
                            }[];
                        };
                    };
                };
                /** @description Default Response */
                403: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            error: string;
                            message: string;
                            allowed?: string[];
                            details?: {
                                field: string;
                                message: string;
                            }[];
                        };
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/sync/reports/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** One sync run, including the raw payload kept from an unknown-shape failure */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Default Response */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            /** Format: uuid */
                            id: string;
                            source: string;
                            /** Format: uuid */
                            departmentId: string | null;
                            startedAt: string;
                            finishedAt: string | null;
                            durationMs: number | null;
                            ok: boolean;
                            shape: string | null;
                            trigger: string;
                            fetched: number;
                            added: number;
                            updated: number;
                            unchanged: number;
                            wentAbsent: number;
                            returned: number;
                            skipped: number;
                            rejected: number;
                            error: string | null;
                            rejections: {
                                row: number;
                                externalId: string | null;
                                errors: {
                                    field: string;
                                    message: string;
                                }[];
                            }[];
                            rawPayload?: unknown;
                            hasRawPayload?: boolean;
                        };
                    };
                };
                /** @description Default Response */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            error: string;
                            message: string;
                            allowed?: string[];
                            details?: {
                                field: string;
                                message: string;
                            }[];
                        };
                    };
                };
                /** @description Default Response */
                403: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            error: string;
                            message: string;
                            allowed?: string[];
                            details?: {
                                field: string;
                                message: string;
                            }[];
                        };
                    };
                };
                /** @description Default Response */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            error: string;
                            message: string;
                            allowed?: string[];
                            details?: {
                                field: string;
                                message: string;
                            }[];
                        };
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/cameras/{id}/trust": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Current trust score, the breakdown that explains it, and the recent trend */
        get: {
            parameters: {
                query?: {
                    days?: number;
                };
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Default Response */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            /** Format: uuid */
                            cameraId: string;
                            externalId: string;
                            name: string;
                            score: number | null;
                            /** @enum {string|null} */
                            band: "trusted" | "degraded" | "untrusted" | "dead" | null;
                            checkedAt: string | null;
                            breakdown: {
                                signals: {
                                    signal: string;
                                    raw: (number | boolean) | null;
                                    quality: number | null;
                                    weight: number;
                                    points: number;
                                    maxPoints: number;
                                    applicable: boolean;
                                    note: string;
                                }[];
                                excluded: {
                                    signal: string;
                                    reason: string;
                                }[];
                                weightsVersion: number | null;
                                pointsTotal: number;
                            };
                            trend: {
                                bucket: string;
                                score: number | null;
                                /** @enum {string|null} */
                                band: "trusted" | "degraded" | "untrusted" | "dead" | null;
                                checks: number;
                                reachableChecks: number;
                            }[];
                        };
                    };
                };
                /** @description Default Response */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            error: string;
                            message: string;
                            allowed?: string[];
                            details?: {
                                field: string;
                                message: string;
                            }[];
                        };
                    };
                };
                /** @description Default Response */
                403: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            error: string;
                            message: string;
                            allowed?: string[];
                            details?: {
                                field: string;
                                message: string;
                            }[];
                        };
                    };
                };
                /** @description Default Response */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            error: string;
                            message: string;
                            allowed?: string[];
                            details?: {
                                field: string;
                                message: string;
                            }[];
                        };
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/trust/summary": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Estate-wide trust distribution, by department and by district */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Default Response */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            total: number;
                            scored: number;
                            unscored: number;
                            bands: {
                                trusted: number;
                                degraded: number;
                                untrusted: number;
                                dead: number;
                            };
                            byDepartment: {
                                /** Format: uuid */
                                departmentId: string | null;
                                departmentCode: string | null;
                                total: number;
                                trusted: number;
                                degraded: number;
                                untrusted: number;
                                dead: number;
                                averageScore: number | null;
                            }[];
                            byDistrict: {
                                district: string | null;
                                total: number;
                                trusted: number;
                                degraded: number;
                                untrusted: number;
                                dead: number;
                                averageScore: number | null;
                            }[];
                        };
                    };
                };
                /** @description Default Response */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            error: string;
                            message: string;
                            allowed?: string[];
                            details?: {
                                field: string;
                                message: string;
                            }[];
                        };
                    };
                };
                /** @description Default Response */
                403: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            error: string;
                            message: string;
                            allowed?: string[];
                            details?: {
                                field: string;
                                message: string;
                            }[];
                        };
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Exchange a badge number and password for a bearer token */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        badgeNo: string;
                        password: string;
                    };
                };
            };
            responses: {
                /** @description Default Response */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            token: string;
                            expiresInSeconds: number;
                            user: {
                                /** Format: uuid */
                                id: string;
                                name: string;
                                badgeNo: string;
                                /** @enum {string} */
                                role: "admin" | "supervisor" | "operator" | "auditor";
                                /** Format: uuid */
                                departmentId: string | null;
                                departmentCode: string | null;
                                capabilities: string[];
                            };
                        };
                    };
                };
                /** @description Default Response */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            error: string;
                            message: string;
                            allowed?: string[];
                            details?: {
                                field: string;
                                message: string;
                            }[];
                        };
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** The signed-in user behind the presented token */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Default Response */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            /** Format: uuid */
                            id: string;
                            name: string;
                            badgeNo: string;
                            /** @enum {string} */
                            role: "admin" | "supervisor" | "operator" | "auditor";
                            /** Format: uuid */
                            departmentId: string | null;
                            departmentCode: string | null;
                            capabilities: string[];
                        };
                    };
                };
                /** @description Default Response */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            error: string;
                            message: string;
                            allowed?: string[];
                            details?: {
                                field: string;
                                message: string;
                            }[];
                        };
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: never;
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export type operations = Record<string, never>;
