/**
 * D3-08 — the scenario export has to be pasteable into the HLD without editing.
 *
 * "Suitable for direct paste" is an acceptance criterion, so it is asserted rather than eyeballed:
 * the heading structure the HLD expects, a provenance table that names every constant, the section 9
 * reconciliation, and no leaked placeholders, NaNs or HTML.
 */
import { describe, expect, it } from 'vitest';
import { CONSTANT_KEYS, SIZING_CONSTANTS } from './constants.js';
import { formatInr, formatInrBand, renderScenarioMarkdown } from './markdown.js';
import { SIZING_PRESETS, presetById } from './presets.js';

const statewide = presetById('statewide');
if (statewide === undefined) throw new Error('statewide preset missing');

const doc = renderScenarioMarkdown({ preset: statewide });

describe('renderScenarioMarkdown (AC 6)', () => {
  it('opens with a title naming the scenario', () => {
    expect(doc.startsWith('# Infrastructure sizing — Statewide (80,000 cameras)')).toBe(true);
  });

  it('warns that the file is generated, so nobody hand-edits it back into disagreement', () => {
    expect(doc).toMatch(/Generated by `npm run export:sizing`/);
    expect(doc).toMatch(/Do not edit by hand/);
    expect(doc).toMatch(/D3-08 \(#31\)/);
  });

  it('carries every section the HLD dimensions need', () => {
    for (const heading of [
      '## 0 · Scenario',
      '## 1 · Backhaul',
      '## 2 · Compute',
      '## 3 · Storage',
      '## 4 · Cost',
      '## 5 · Reconciliation with `PROJECT.md` section 9',
      '## 6 · Every constant, and where it came from',
      '## 7 · What this model does not claim',
    ]) {
      expect(doc, heading).toContain(heading);
    }
  });

  it('is plain CommonMark — no HTML, no front matter, no template leakage', () => {
    expect(doc).not.toMatch(/<[a-z][^>]*>/);
    expect(doc.startsWith('---')).toBe(false);
    expect(doc).not.toMatch(/undefined|NaN|\[object Object\]|\$\{/);
  });

  it('lists every constant the model read, with its provenance', () => {
    // The provenance table is the credibility. If a constant reaches the document without one,
    // the document is worth no more than the static table it replaces.
    expect(doc).toMatch(/\| Key \| Constant \| Value \| Provenance \| Source \|/);
    for (const key of ['sightingRowBytes', 'cropBytesMeasured', 'videoBitrateMbps']) {
      expect(doc, key).toContain(`\`${key}\``);
    }
    expect(doc).toMatch(/\*\*measured\*\*/);
    expect(doc).toMatch(/\| listed \|/);
    expect(doc).toMatch(/\| assumed \|/);
  });

  it('reproduces the section 9 figures in the reconciliation table', () => {
    expect(doc).toMatch(/160 Gbps central video \| \*\*160\.00 Gbps\*\*/);
    expect(doc).toMatch(/\*\*1\.28 Gbps\*\*/);
    expect(doc).toMatch(/\*\*125\.0x\*\*/);
    expect(doc).toMatch(/~960 GPUs \| \*\*960\*\*/);
    expect(doc).toMatch(/2,160x/);
  });

  it('states the 500x spread, so no reader mistakes the mean for a typical camera', () => {
    expect(doc).toMatch(/\*\*500x\*\*/);
    expect(doc).toContain('cam04');
    expect(doc).toContain('cam03');
    expect(doc).toMatch(/describes no actual camera/);
  });

  it('names the tickets its measured numbers came from', () => {
    for (const ticket of ['D1-09 #13', 'D2-01 #15', 'D2-02 #16', 'D1-03', 'D3-07', 'D3-05 #28']) {
      expect(doc, ticket).toContain(ticket);
    }
  });

  it('refuses to present a CUDA figure as ours', () => {
    expect(doc).toMatch(/no NVIDIA GPU on this machine/);
    expect(doc).toMatch(/monkeypatching `torch`/);
  });

  it('says plainly that nothing was re-measured for this document', () => {
    expect(doc).toMatch(/No figure here was measured today/);
    expect(doc).toMatch(/that re-run belongs to D4-04/i);
  });

  it('marks the crop figure as a band and the metadata figure as not compressed', () => {
    expect(doc).toMatch(/3 KB and 15 KB/);
    expect(doc).toMatch(/columnar compression is not enabled/);
  });

  it('renders every preset without leaking a placeholder', () => {
    for (const p of SIZING_PRESETS) {
      const out = renderScenarioMarkdown({ preset: p });
      expect(out.length, p.id).toBeGreaterThan(4_000);
      expect(out, p.id).not.toMatch(/undefined|NaN/);
      expect(out, p.id).toContain(p.label);
    }
  });

  it('can drop the optional sections for a shorter deck paste', () => {
    const short = renderScenarioMarkdown({
      preset: statewide,
      includeSection9: false,
      includeProvenance: false,
    });
    expect(short).not.toContain('## 5 · Reconciliation');
    expect(short).not.toContain('## 6 · Every constant');
    expect(short).toContain('## 1 · Backhaul');
  });

  it('reflects an override in both the numbers and the provenance table', () => {
    const overridden = renderScenarioMarkdown({
      preset: statewide,
      overrides: { videoBitrateMbps: 4 },
    });
    // 80,000 x 4 Mbps = 320 Gbps.
    expect(overridden).toMatch(/\*\*320\.00\*\*/);
    expect(overridden).toMatch(/Overridden by the reader/);
  });
});

describe('formatInr', () => {
  it('uses Indian numbering, because the reader budgets in crore and lakh', () => {
    expect(formatInr(1_500)).toBe('INR 1,500');
    expect(formatInr(250_000)).toBe('INR 2.50 lakh');
    expect(formatInr(62_400_000)).toBe('INR 6.24 crore');
  });

  it('collapses a band with no width to a single figure', () => {
    expect(formatInrBand({ low: 100, high: 100 })).toBe('INR 100');
    expect(formatInrBand({ low: 100, high: 200 })).toBe('INR 100 – INR 200');
  });
});

describe('the registry itself', () => {
  it('exports one key per registry entry', () => {
    expect(CONSTANT_KEYS.length).toBe(Object.keys(SIZING_CONSTANTS).length);
  });
});
